### ISSUE TITLE
Projekt erstellen 

### ISSUE THREAD

**Issue by pat-he** [whiteducksoftware/Praktikumsprojekt2023#1]
[Praktikums-Projekt](https://github.com/whiteducksoftware/wd-pm-and-education/issues/268): Aufgabe 1
Erste .NET API erstellen und erste TODO-Items anlegen und löschen.
```[tasklist]
### Tasks
- [x] Projekt erstellen
- [x] .Net API anlegen für eine "Todo-Verwaltung"
- [x] Entityklasse "TodoItem" in Models Ordner erstellen
- [x] TodoContext - Verbindung zum Entity-Framework
- [x] Endpunkte in "TodoItemsContoller.cs" angelegt und mit Funktionalität befüllt: get, post, delete, put
- [x] Konzept der Lösung besprechen
- [x] Konzept umsetzen: Erste Todo-Items anlegen und wieder löschen
- [x] Code Review mit Betreuer ( mit Simon oder Suad )
- [x] Resultat dokumentieren
```
