### ISSUE TITLE
Ausbau: Azure SQL Database

### ISSUE THREAD

**Issue by VelascoPatrik** [whiteducksoftware/Praktikumsprojekt2023#2]
[Praktikums-Projekt](https://github.com/whiteducksoftware/wd-pm-and-education/issues/268): Aufgabe 2
Ziel: SQL Datenbank in Azure erstellen und mit Projekt verknüpfen
```[tasklist]
### Tasks
- [x] Tutorial 1: Azure SQL Datenbank erstellen
- [x] Tutorial 2: Entity Framework Core mit SQL Datenbank verbinden
- [x] Tutorial 3: Entity Framework Core Migration
- [x] Tutorial 4: Repository Pattern
- [x] Konzept besprechen
- [x] Eigene Azure Datenbank erstellen
- [x] Connection implementieren in C#
- [x] Repository-Muster erstellen
- [x] Codereview ( mit Simon oder Suad )
- [x] Resultat dokumentieren
```
