### ISSUE TITLE
Ausbau: Azure Active Directory Authentifizierung

### ISSUE THREAD

**Issue by VelascoPatrik** [whiteducksoftware/Praktikumsprojekt2023#7]
[Praktikums-Projekt](https://github.com/whiteducksoftware/wd-pm-and-education/issues/268): Aufgabe 4

 Nur authentifierte AAD Nutzer sollen Zugriff auf die API Endpunkte haben

```[tasklist]
### Tasks
- [x] Create App Registration (Tutorial)
- [x] Configure App Registration (Tutorial)
- [x] Use App Registration in .NET Project (Tutorial)
- [x] Token Implicit Flow als Request (Tutorial)
- [x] Konzept-Lösung erstellen und besprechen
- [x] Lösung implementieren
- [x] Code Review
- [ ] Dokumentation
- [ ] Done
```
